### ISSUE TITLE
Calculate confusion matrix on entire dataset

### ISSUE THREAD

**Issue by cleversonahum** [cleversonahum/breast_cancer_diagnosis#5]
Paper calculates the confusion matrix over the entire dataset (see section 6.1), I don't think it's correct, but let's implement it as they did since our goal is to reimplement the code. It is important to define the variables TP, FP, TN and FN (vide section 4) since they are used as basis to calculate the metrics defined in 4.1-4.9. Besides the definition of variables, it should show a table with the confusion matrix values.

**Comment by aaneto** [comment]
Posso pegar essa.

**Comment by aaneto** [comment]
#8
