### ISSUE TITLE
Calculate performance metrics

### ISSUE THREAD

**Issue by cleversonahum** [cleversonahum/breast_cancer_diagnosis#6]
Calculate performance metrics defined in the paper from sections 4.1-4.8 (does not include the ROC curve). Depends on issue #5 .

**Comment by cleversonahum** [comment]
@aaneto tu já resolveu essa issue no commit 2996ef949812c2c0abcb2e0dcd61e2049263a732 certo?

**Comment by aaneto** [comment]
Acredito que está resolvido sim.

**Comment by aaneto** [comment]
#8
