### ISSUE TITLE
Create ROC curve

### ISSUE THREAD

**Issue by cleversonahum** [cleversonahum/breast_cancer_diagnosis#7]
Plot ROC curve as defined in paper section 4.9.  It should be similar to figure 18 and 19. Depends on issues #5 and #6 .

**Comment by cleversonahum** [comment]
@felipebastosb I've searched a little and it seems that [Scikit already has a function to plot ROC curve](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.plot_roc_curve.html#sklearn.metrics.plot_roc_curve). So, it can help you. Another thing is to calculate the  AUC value using the [function of scikit](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_auc_score.html#sklearn.metrics.roc_auc_score). You can calculate the AUC for each of the classifiers and add them to the dataframe to make its value appears in the plot of cell 25 (commit 351a894554e515942bb25a27aad574eaa2cd8bbc). I've changed a little bit the structure to support multiple classifiers, so if you have any difficult let me know.

**Comment by felipebastosb** [comment]
@cleversonahum I calculated the ROC curves and AUC values. I didn't add in the figure of cell 25, because I got confused with the data structure.

**Comment by cleversonahum** [comment]
Closed in e30ab0b36d61ba1b8c561e9476e6bf890e0e011f
